### ISSUE TITLE
Table markdown

### ISSUE THREAD

**Issue by vesnikos** [urbanbigdatacentre/ubdc-web-starter-kit#14]
The table markdown is not rendered properly:

~~~markdown
| Parameter | Value |
| --- | --- |
| Host | `172.20.67.58` |
| Port | `5432` |
| Database | `<your_guid>` |
| Username | `<your_guid>` |
| Password | `<your_password>` |
~~~

renders as 
![image](https://github.com/urbanbigdatacentre/ubdc-web-starter-kit/assets/6684178/250ea3ba-9281-4e15-9f85-408db37d884a)

should be:
![image](https://github.com/urbanbigdatacentre/ubdc-web-starter-kit/assets/6684178/f4ff9e31-4390-46af-a6c2-9744c18af5be)

**Comment by andymithamclarke** [comment]
Resolved in commit [56ee4d8](https://github.com/urbanbigdatacentre/ubdc-web-starter-kit/commit/56ee4d875af3398e5a0d979dad0e858eabd03334) - see here for how it works [github-flavoured.md](https://github.com/urbanbigdatacentre/ubdc-web-starter-kit/blob/docs/docs/examples/github-flavoured.md)

![Screenshot 2023-07-05 at 14 41 24](https://github.com/urbanbigdatacentre/ubdc-web-starter-kit/assets/56840824/30b2c3b5-3664-4abb-b44b-a23e431b9794)
