### ISSUE TITLE
Emphasis: Italics are not rendered

### ISSUE THREAD

**Issue by vesnikos** [urbanbigdatacentre/ubdc-web-starter-kit#16]
~~~Markdown
_italics_
*italics*
~~~
is not rendered

byt extansion also italics+bold does not work:
~~~markdown
***bold+italic*** 
___bold+italic___  
__*bold+italic*__  
asdf***bold+italic***asdf  
~~~

**Comment by andymithamclarke** [comment]
Resolved in commit - [e58a62e](https://github.com/urbanbigdatacentre/ubdc-web-starter-kit/commit/e58a62e1469d26da167c19bd9f8e6f37113a5ca3) 

![Screenshot 2023-07-07 at 10 40 01](https://github.com/urbanbigdatacentre/ubdc-web-starter-kit/assets/56840824/64d14644-759f-4298-88ef-059bf0b8b9e3)
