### ISSUE TITLE
Add Admonitions

### ISSUE THREAD

**Issue by vesnikos** [urbanbigdatacentre/ubdc-web-starter-kit#2]
feature from https://docusaurus.io/docs/markdown-features/admonitions

~~~md
:::note

Some **content** with _Markdown_ `syntax`. Check [this `api`](#).

:::

:::tip

Some **content** with _Markdown_ `syntax`. Check [this `api`](#).

:::

:::info

Some **content** with _Markdown_ `syntax`. Check [this `api`](#).

:::

:::caution

Some **content** with _Markdown_ `syntax`. Check [this `api`](#).

:::

:::danger

Some **content** with _Markdown_ `syntax`. Check [this `api`](#).

:::
~~~
![image](https://github.com/urbanbigdatacentre/ubdc-web-starter-kit/assets/6684178/4e64722f-0fa0-4c03-ba87-edf0ad793ab8)

**Comment by andymithamclarke** [comment]
Feature added in commit [540e926](https://github.com/urbanbigdatacentre/ubdc-web-starter-kit/commit/540e926716c47663fe3ea7764b709f08330f577b)

See [docs/examples/admonitions.md](docs) for more info.

![Screenshot 2023-06-30 at 16 29 12](https://github.com/urbanbigdatacentre/ubdc-web-starter-kit/assets/56840824/67198ce5-92c6-4961-8530-59fbbd9b5893)
