### ISSUE TITLE
Add diagrams

### ISSUE THREAD

**Issue by vesnikos** [urbanbigdatacentre/ubdc-web-starter-kit#3]
Feature from https://docusaurus.io/docs/markdown-features/diagrams

See the [Mermaid syntax documentation](https://mermaid-js.github.io/mermaid/#/./n00b-syntaxReference) for more information on the Mermaid syntax.

~~~md
```mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
```
~~~

![image](https://github.com/urbanbigdatacentre/ubdc-web-starter-kit/assets/6684178/cf449c29-900b-4490-ba76-dec91ce78725)

**Comment by andymithamclarke** [comment]
Resolved in commit - [cfc29d4](https://github.com/urbanbigdatacentre/ubdc-web-starter-kit/commit/cfc29d490e2ac1d020f37877a66462d0b0a22792) 

See examples at [docs/examples/diagrams](https://github.com/urbanbigdatacentre/ubdc-web-starter-kit/blob/docs/docs/examples/diagrams.md)
![Screenshot 2023-07-06 at 09 59 31](https://github.com/urbanbigdatacentre/ubdc-web-starter-kit/assets/56840824/d751d9c5-e185-49b6-966d-d19a564433af)
