### ISSUE TITLE
Add Search capability

### ISSUE THREAD

**Issue by vesnikos** [urbanbigdatacentre/ubdc-web-starter-kit#5]
Feature from https://docusaurus.io/docs/search

search requires processing power (or not if search cache data is small enough to be carried client-side); see following links for inspiration

🥇 [Algolia DocSearch](https://docusaurus.io/docs/search#using-algolia-docsearch) (official)
👥 [Typesense DocSearch](https://docusaurus.io/docs/search#using-typesense-docsearch)
👥 [Local Search](https://docusaurus.io/docs/search#using-local-search)
👥 [Your own SearchBar component](https://docusaurus.io/docs/search#using-your-own-search)

**Comment by andymithamclarke** [comment]
![Screenshot 2023-07-11 at 11 39 18](https://github.com/urbanbigdatacentre/ubdc-web-starter-kit/assets/56840824/2f1236f7-11fc-4fe2-8e3d-e0bd0b7c6fd7)
