### ISSUE TITLE
Add Tags

### ISSUE THREAD

**Issue by vesnikos** [urbanbigdatacentre/ubdc-web-starter-kit#7]
Add tagging system parsed from MD metadata

**Comment by andymithamclarke** [comment]
Feature added in commit [540e926](https://github.com/urbanbigdatacentre/ubdc-web-starter-kit/commit/540e926716c47663fe3ea7764b709f08330f577b)


![Screenshot 2023-06-30 at 16 33 30](https://github.com/urbanbigdatacentre/ubdc-web-starter-kit/assets/56840824/e106f4fe-031e-4ebc-85f7-30cb1918969d)

**Comment by andymithamclarke** [comment]
Start using tags by adding them to the metadata at the top of each markdown file like follows 

----
... 
tags: [tag1, tag2]
----
