### ISSUE TITLE
Make Sections collapsible

### ISSUE THREAD

**Issue by vesnikos** [urbanbigdatacentre/ubdc-web-starter-kit#9]
![image](https://github.com/urbanbigdatacentre/ubdc-web-starter-kit/assets/6684178/41170d32-54af-4925-bb46-dfcb8fe91977)

**Comment by andymithamclarke** [comment]
Implemented in commit [0a3ec46](https://github.com/urbanbigdatacentre/ubdc-web-starter-kit/commit/0a3ec4689ce933147b9e77d96fd2b5228f657a19)
